version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "8801:8080"
      - "8811:8081"
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    ipam:
      config:
        - subnet: 172.81.0.0/16
